### ISSUE TITLE
RemnantSaveManager.exe won't launch

### ISSUE THREAD

**Issue by Zer1an** [Razzmatazzz/RemnantSaveManager#64]
Opening RemnantSaveManager.exe does nothing.

It's the same for me, and my friend.
We both have .NET Framework 4.7.2 Runtime or later version installed.

**Comment by Zer1an** [comment]
Here's the error log he got by launching earlier version

ERROR REPORT
The following errors were encountered during this operation.
* [08/06/2023 15:26:27] System.Deployment.Application.InvalidDeploymentException (Zone)
- Deployment and application do not have matching security zones.
- Source: System.Deployment
- Record stack changes:
at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by hwfanatic** [comment]
I'm fairly certain this only happens when RSM cannot locate the game.

I wanted to check my backups but didn't have the game installed - the result was a crash with an exception 0xe0434352 in KERNELBASE.dll which was logged in Windows.
After I have installed the game through Epic Game Launcher, I had no issues running RSM.

I'm necroing this thread in case somebody encounters a similar issue.

**Comment by PMortis2** [comment]
im necroposting aswell in case someone is gonne experience crashes with every inteaction related to the backup.
as mentioned, in my case every interaction with older backups were leading to a crash, and if i was trying to recover a backup, i would just lose the profile.
once i copied manually the backup into the game folder and made a backup with RSM, everything was working fine with the new and old backups, i wonder why now that i manually imported my old backup it works with no problem, and before that when i launched the game and create a save, it would still be crashing while trying to recover the backup and even just by clicking on "open in explorer".
